(define (problem hunt-animal)
  (:domain survival-island)
  (:objects 
    fruits vegetables food poisonous-berries scurvy-preventers
    fish insects small-animals protein nutrients mollusks clams oysters crabs muscles reptiles birds insects beetles spiders
    water-shallow water-huntable-animal)
  (:init
    (food fruits)
    (food vegetables)
    (fresh-fruit fruits)
    (poisonous-food poisonous-berries)
    (scurvy-symptoms scurvy-preventers)
    (huntable-animal fish)
    (huntable-animal insects)
    (huntable-animal small-animals)
    (protein nutrients fish)
    (protein nutrients mollusks)
    (protein nutrients clams)
    (protein nutrients oysters)
    (protein nutrients crabs)
    (protein nutrients muscles)
    (huntable-animal reptiles)
    (huntable-animal birds)
    (insects insect)
    (huntable-animal insects)
    (huntable-animal insects)
    (huntable-animal reptiles)
    (protein nutrients insects)
    (cooked-shellfish clams)
    (cooked-shellfish oysters)
    (cooked-shellfish crabs)
    (cooked-shellfish muscles)
    (test-food-poisonous poisonous-food)
  )
  (:goal
    (huntable-animal food)
  )
)